schema: "classroom50/repo-config/v1"
classroom: "50c-202620"
assignment: "m02-programming-assignment-1"
secret: "krfy4503"
owner:
  username: "ChadCarmickle"
  id: 54717796
  accepted_at: "2026-08-31T20:08:01Z"
source:
  owner: "CSCI202FW"
  owner_id: 170132889
  repo: "M02-Assign-1-Starter"
  branch: "main"
